version: '3'
services:

  #THE FORGOTTEN SERVER
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: tfs
    container_name: tfs
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: tfs
      SERVICE_TAGS: dev
    working_dir: /srv
    links:
      - database
    networks:
      - app-network

  #PHP Service
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: premium-gesior
    container_name: website
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: website
      SERVICE_TAGS: dev
    working_dir: /var/www
    links:
      - database
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - C:/xampp/htdocs/server:/usr/local/server
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  database:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: premium-gesior
      MYSQL_ROOT_PASSWORD: gesior
      SERVICE_TAGS: dev
      SERVICE_NAME: database
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
