version: '3'
services:

  #THE FORGOTTEN SERVER
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    container_name: server
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: server
      SERVICE_TAGS: dev
    working_dir: /srv
    links:
      - database
    networks:
      - app-network

  #PHP Service
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: premium-gesior
    container_name: website
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: website
      SERVICE_TAGS: dev
    working_dir: /var/www
    links:
      - database
    volumes:
      - ./website:/var/www
      - ./server:/usr/local/server
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: jwilder/nginx-proxy
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./website:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - app-network
    depends_on:
      - website

  #MySQL Service
  database:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: premium-gesior
      MYSQL_ROOT_PASSWORD: gesior
      SERVICE_NAME: database
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
